FROM 766267172432.dkr.ecr.us-east-1.amazonaws.com/automodel@sha256:02f4ccbcb23c5e90641fd9583aa9ca2ebfec1c6d1c5e8320c5179c507a01d171

USER root
ENV NO_VCS_VERSION=1 \
    UV_NO_BUILD_ISOLATION=1 \
    UV_OFFLINE=1
RUN . /opt/venv/env.sh && \
    unset UV_OFFLINE UV_PROJECT && \
    uv pip install '.[vlm-media]' && \
    chown -R 65532:65532 /opt/uv_cache /opt/venv /opt/Automodel

COPY <<EOF /opt/venv/env.sh
export UV_PROJECT_ENVIRONMENT=/opt/venv
export NO_VCS_VERSION=1
export UV_NO_BUILD_ISOLATION=1
export UV_OFFLINE=1
unset UV_PROJECT
export PATH="/opt/venv/bin:$PATH"
export UV_LINK_MODE=copy
export PATH="/usr/local/bin:$PATH"
EOF
RUN chmod +x /opt/venv/env.sh
USER 65532:65532
RUN test "$(git -C /opt/Automodel rev-parse HEAD)" = cf4f0be2e8f7969072801e10f94834ad56151c78 && \
    test -w /opt/uv_cache && \
    . /opt/venv/env.sh && \
    uv pip install '.[vlm-media]'
WORKDIR /opt/Automodel
